### ISSUE TITLE
Refresh the menu after progress reset

### ISSUE THREAD

**Issue by mikeymike** [php-school/php-workshop#86]
Currently after we reset progress and go back the progress is still there, we should rebuild the menu so it's up to date as soon as the user goes back.

**Comment by AydinHassan** [comment]
I noticed this but ignored it, I have no idea how to solve it 😖

**Comment by mikeymike** [comment]
Had a look this morning, had me stumped too :disappointed: ... Maybe as a temp fix we just output something like ... `Please exit the application and reopen for changes to take effect`

**Comment by AydinHassan** [comment]
Fixed with #131
