### ISSUE TITLE
My solution to Program 4 passes when it should fail.

### ISSUE THREAD

**Issue by StyxOfDynamite** [php-school/php-workshop#98]
The first time I ran `learnyouphp verfiy program4.php`
```
  vagrant@scotchbox:/var/www/public/phpschool$ learnyouphp verify program4.php
   ✔ Check: File Exists Check
   ✔ Check: PHP Code Check
   ✔ Check: Code Parse Check
   ✗ Check: CLI Program Runner
    ACTUAL
    "dat
    words.dat
    wrrrrongdat
    w00t.dat
    data.dat
    learnyouphp.dat
    "

    EXPECTED
    "words.dat
    w00t.dat
    data.dat
    learnyouphp.dat
    "

   FAIL!

  Your solution to Filtered LS didn't pass. Try again!
```

The second time I run the `verify` command it passed. Same code under I assume different test conditions?

```
vagrant@scotchbox:/var/www/public/phpschool$ learnyouphp verify program4.php
 ✔ Check: File Exists Check
 ✔ Check: PHP Code Check
 ✔ Check: Code Parse Check
 ✔ Check: CLI Program Runner

 PASS!
```

**Comment by AydinHassan** [comment]
Hi @StyxOfDynamite The arguments given to you are slightly randomised, so it seems you are only filtering by the file ending with `dat` and not actually the file extension `dat`. On the first invocation you received a file, the first one `dat` which ends with `dat` but is not actually the file extension!

The second time no files were given to you which ended with `dat` but were not the extension, if that makes sense?

**Comment by StyxOfDynamite** [comment]
Thanks, I got my code working by including the `.` in the string I was looking for. Just thought I'd report the false positive as it might be confusing to be told your code passes when infact there's a bug. (like mine)

**Comment by AydinHassan** [comment]
I guess we could always make sure that a file named `dat` is included. I'll keep this open and see if someone can tackle it :)

**Comment by StyxOfDynamite** [comment]
Nice work :+1:
